### ISSUE TITLE
script src path correction in color-clock/index.html line 16

### ISSUE THREAD

**Issue by iamtash** [learn-co-curriculum/npm-lab#11]
should be `<script src="node_modules/moment/moment.js"></script>` otherwise `moment.js` will not load

**Comment by swdecker** [comment]
came here to raise this issue, and agree that this path is causing student problems

**Comment by rrcobb** [comment]
Looks like this was addressed by @thuyanduong in https://github.com/learn-co-curriculum/npm-lab/commit/e5089b0ce59347c6c10f65ae7fb7b2f9f19db24e

Thanks for raising the issue!
