### ISSUE TITLE
No Fork or Submit

### ISSUE THREAD

**Issue by dmcgrann** [learn-co-curriculum/npm-lab#4]
Hi,

The lab isn't giving me credit for Fork or Submit, but it does show tests passing. I have tried the   steps in Help menu a couple of times (deleting the repo and re-forking), but that hasn't worked either. Here's the latest repo:

https://github.com/dmcgrann/npm-lab-v-000

Thanks,

David

**Comment by maxwellbenton** [comment]
Hi @dmcgrann,

Thank you for providing this feedback. On further investigation, it looks like the way this lab is designed caused problems with Learn registering completion. To resolve this, we've changed this from a lab to a code-along with additional guidance and moved the solution files into a sub-folder. This should remove the requirement to run tests, but still covers what was tested as well as some additional details. It should also trigger a different set of lights and behaviors in Learn, which should resolve this issue.

We apologize for and frustration this lab may have caused you, but we appreciate you taking the time to provide feedback and help improve our curriculum!
