### ISSUE TITLE
local tests

### ISSUE THREAD

**Issue by DavidAlexSiler** [learn-co-curriculum/npm-lab#8]
Not sure how to pass the local tests. The browser test works fine but it doesnt pass it up to learn.

**Comment by maxwellbenton** [comment]
Hi @DavidAlexSiler,

Thank you for providing this feedback. On further investigation, it looks like the way this lab is designed caused problems with Learn registering completion. To resolve this, we've changed this from a lab to a code-along with additional guidance and moved the solution files into a sub-folder. This should remove the requirement to run tests, but still covers what was tested as well as some additional details.

We apologize for and frustration this lab may have caused you, but we appreciate you taking the time to provide feedback and help improve our curriculum!
